SG-36248 PHASE 2 - removing python2
shotgunsoftware/tk-shotgun-launchvredreview pull request #13
Opened 2024-10-01 12:14 UTC by eduardoChaucaGallegos

- Removing Python2 checklist from [plan](https://wiki.autodesk.com/display/SHOT/Plan+execution+Py2+FY25Q3)

2024-10-01 13:31 UTC, carlos-villavicencio-adsk approved these changes

2024-10-01 15:52 UTC, julien-lang approved these changes

2024-10-01 16:11 UTC, julien-lang requested changes
README badge

2024-10-01 17:56 UTC, julien-lang submitted a review, later dismissed

2024-10-01 17:56 UTC, julien-lang commented on README.md
> +[![Python 3.7](https://img.shields.io/badge/python-3.7-blue.svg)](https://www.python.org/)
3.7, 3.9, 3.10

2024-10-03 16:32 UTC, julien-lang approved these changes

2024-10-31 15:38 UTC, merged