SHOT-3556
shotgunsoftware/tk-shotgun-launchvredreview pull request #3
Opened 2020-11-23 19:14 UTC by staceyoue

* Simplified logic in `init_app` method
* Modified `_launch_via_hook` method to load in a Version or Playlist context in SG Panel when launching VRED for review
* Renamed config value from `viewer_extensions` to `accepted_published_file_types` and now specifies the PublishedFileType name instead of the file extension to allow easier filtering at the API level

@rob-aitchison I originally wanted to move the config option `accepted_published_file_types` to tk-vred config instead of this app, since the engine needs this value as well; however, I couldn't get this app to retrieve the config from tk-vred -- it was just empty, but was OK when accessing from tk-vred itself. Can you not access engine config settings from an app?

2020-11-23 20:21 UTC, rob-aitchison commented
Hey @staceyoue, for clarity, are you trying to access the engine config setting before the engine is running?

2020-11-23 20:34 UTC, staceyoue commented
@rob-aitchison I believe that is what is happening, we would need to access the config setting in the app.py method `_launch_via_hook`. Ideally tk-shotgun-launchvredreview and tk-vred could share the config settings `accepted_published_file_types`

2020-11-23 20:41 UTC, rob-aitchison commented
@staceyoue , yes, agreed, let's try and figure out a way to use only the engine location for settings if possible.

2021-04-23 18:27 UTC, rob-aitchison commented on app.py
> +        # Extract the path on local disk for the published file that will be openedin VRED
typo - missing space openedin

2021-04-23 18:29 UTC, rob-aitchison requested changes
One typo spotted, otherwise all good, thanks!

2021-04-23 19:34 UTC, rob-aitchison submitted a review, later dismissed
Thanks! 👍🏻

2021-04-26 10:09 UTC, barbara-darkshot submitted a review, later dismissed
LGTM!

2021-04-26 10:16 UTC, barbara-darkshot commented
hey @staceyoue and @rob-aitchison , I think this maybe help you to access tk-vred settings from this app even if the engine has not yet been started: https://github.com/shotgunsoftware/tk-alias/blob/master/engine.py#L488-L501
In my case, I'm accessing the settings from another project but you could use the same logic to get tk-vred settings and avoid introducing this duplicate setting inside of this app

2021-04-26 17:19 UTC, staceyoue commented
> hey @staceyoue and @rob-aitchison , I think this maybe help you to access tk-vred settings from this app even if the engine has not yet been started: https://github.com/shotgunsoftware/tk-alias/blob/master/engine.py#L488-L501
> In my case, I'm accessing the settings from another project but you could use the same logic to get tk-vred settings and avoid introducing this duplicate setting inside of this app

Thank Babara! With this suggestion I was able to define the settings only in the tk-vred engine, and this app will be able to then access those settings, to avoid duplicating it.

2021-04-26 17:26 UTC, rob-aitchison approved these changes
Yes, looks great, thanks again @barbara-darkshot for the suggestion and @staceyoue for the quick turnaround! 👍🏻

2021-04-26 17:33 UTC, merged